//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParadoxPower.Languages {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ParadoxPower.Languages.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似  和  的本地化字符串。
        /// </summary>
        public static string Parse_And {
            get {
                return ResourceManager.GetString("Parse.And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不区分大小写 的本地化字符串。
        /// </summary>
        public static string Parse_CaseInsensitive {
            get {
                return ResourceManager.GetString("Parse.CaseInsensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 子句 的本地化字符串。
        /// </summary>
        public static string Parse_Clause {
            get {
                return ResourceManager.GetString("Parse.Clause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右花括号 的本地化字符串。
        /// </summary>
        public static string Parse_ClosingBrace {
            get {
                return ResourceManager.GetString("Parse.ClosingBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注释 的本地化字符串。
        /// </summary>
        public static string Parse_Comment {
            get {
                return ResourceManager.GetString("Parse.Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 无法解析, 因为:  的本地化字符串。
        /// </summary>
        public static string Parse_CompoundCouldNotBeParsedBecause {
            get {
                return ResourceManager.GetString("Parse.CompoundCouldNotBeParsedBecause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此处应为:  的本地化字符串。
        /// </summary>
        public static string Parse_Expected {
            get {
                return ResourceManager.GetString("Parse.Expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; 未闭合 的本地化字符串。
        /// </summary>
        public static string Parse_NotClosed {
            get {
                return ResourceManager.GetString("Parse.NotClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左花括号 的本地化字符串。
        /// </summary>
        public static string Parse_OpeningBrace {
            get {
                return ResourceManager.GetString("Parse.OpeningBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作符 的本地化字符串。
        /// </summary>
        public static string Parse_Operator {
            get {
                return ResourceManager.GetString("Parse.Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  或者  的本地化字符串。
        /// </summary>
        public static string Parse_Or {
            get {
                return ResourceManager.GetString("Parse.Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他错误信息:  的本地化字符串。
        /// </summary>
        public static string Parse_OtherErrors {
            get {
                return ResourceManager.GetString("Parse.OtherErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解析器回溯到:  的本地化字符串。
        /// </summary>
        public static string Parse_ParserBacktrackedAfter {
            get {
                return ResourceManager.GetString("Parse.ParserBacktrackedAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 带引号的字符串 的本地化字符串。
        /// </summary>
        public static string Parse_QuotedString {
            get {
                return ResourceManager.GetString("Parse.QuotedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语句 的本地化字符串。
        /// </summary>
        public static string Parse_Statement {
            get {
                return ResourceManager.GetString("Parse.Statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符串 的本地化字符串。
        /// </summary>
        public static string Parse_String {
            get {
                return ResourceManager.GetString("Parse.String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此处不应为:  的本地化字符串。
        /// </summary>
        public static string Parse_Unexpected {
            get {
                return ResourceManager.GetString("Parse.Unexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知错误 的本地化字符串。
        /// </summary>
        public static string Parse_UnknownErrors {
            get {
                return ResourceManager.GetString("Parse.UnknownErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空白字符 的本地化字符串。
        /// </summary>
        public static string Parse_Whitespace {
            get {
                return ResourceManager.GetString("Parse.Whitespace", resourceCulture);
            }
        }
    }
}
