//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParadoxPower.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ParadoxPower.Languages.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  和 .
        /// </summary>
        public static string Parse_And {
            get {
                return ResourceManager.GetString("Parse.And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 子句.
        /// </summary>
        public static string Parse_Clause {
            get {
                return ResourceManager.GetString("Parse.Clause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 右花括号.
        /// </summary>
        public static string Parse_ClosingBrace {
            get {
                return ResourceManager.GetString("Parse.ClosingBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注释.
        /// </summary>
        public static string Parse_Comment {
            get {
                return ResourceManager.GetString("Parse.Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 无法解析, 因为: .
        /// </summary>
        public static string Parse_CompoundCouldNotBeParsedBecause {
            get {
                return ResourceManager.GetString("Parse.CompoundCouldNotBeParsedBecause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此处应为: .
        /// </summary>
        public static string Parse_Expected {
            get {
                return ResourceManager.GetString("Parse.Expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; 未闭合, 位置: {1}.
        /// </summary>
        public static string Parse_NotClosed {
            get {
                return ResourceManager.GetString("Parse.NotClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 左花括号.
        /// </summary>
        public static string Parse_OpeningBrace {
            get {
                return ResourceManager.GetString("Parse.OpeningBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作符.
        /// </summary>
        public static string Parse_Operator {
            get {
                return ResourceManager.GetString("Parse.Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  或者 .
        /// </summary>
        public static string Parse_Or {
            get {
                return ResourceManager.GetString("Parse.Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 其他错误信息: .
        /// </summary>
        public static string Parse_OtherErrors {
            get {
                return ResourceManager.GetString("Parse.OtherErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 解析器回溯到: .
        /// </summary>
        public static string Parse_ParserBacktrackedAfter {
            get {
                return ResourceManager.GetString("Parse.ParserBacktrackedAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 带引号的字符串.
        /// </summary>
        public static string Parse_QuotedString {
            get {
                return ResourceManager.GetString("Parse.QuotedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语句.
        /// </summary>
        public static string Parse_Statement {
            get {
                return ResourceManager.GetString("Parse.Statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字符串.
        /// </summary>
        public static string Parse_String {
            get {
                return ResourceManager.GetString("Parse.String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此处不应为: .
        /// </summary>
        public static string Parse_Unexpected {
            get {
                return ResourceManager.GetString("Parse.Unexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未知错误.
        /// </summary>
        public static string Parse_UnknownErrors {
            get {
                return ResourceManager.GetString("Parse.UnknownErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 空白字符.
        /// </summary>
        public static string Parse_Whitespace {
            get {
                return ResourceManager.GetString("Parse.Whitespace", resourceCulture);
            }
        }
    }
}
